### PR TITLE
feature/LEAF-1708: Align Admin UI With Figma Design

### PR DESCRIPTION
**Pull request by cameron-chilton**
Updates to User Access page to align existing Admin UI with Figma prototype:

- edits to left and right side nav containers and their content
- related style changes to SCSS
- edits to User Access Groups page: changed card colors, changed font weights. Browser now matches Figma.
- added flex display properties to cards for User Groups

Figma:
Screen Shot 2020-07-29 at 5 28 35 PM

Browser Screenshot:
Screen Shot 2020-08-04 at 12 24 10 PM

### CODE REVIEW

**Comment by fiorine** [comment]
Screen Shot 2020-08-05 at 9 45 25 AM
- incorrect card layout in the System Administrators subsection (should use 2 columns)
- incorrect font style on the "User Access" in the breadcrumbs—should be H1, **Bold** instead of Medium
- incorrect font style on the "Admin" in the breadcrumbs—should be H1, Regular instead of Medium
- increase margin between breadcrumbs and the first subheader
- replace "lastName, firstName" with "firstName lastName"
- add Service Chiefs panel on the right, placeholder cards with subheader in the main zone, and the nav item on the left
Screen Shot 2020-08-05 at 9 47 46 AM
- card component shouldn't have active/visited state (remove thick blue border)
Screen Shot 2020-08-05 at 9 48 42 AM
- left sidebar items should have an active indicator (blue vertical bar on the left) instead of the thick blue border
- filtering doesn't work—when I tap on either one of the items on the left sidebar, nothing happens
@cameron-chilton @dastan-rahimi

**Comment by fiorine** [comment]
The thick blue border still shows on the cards and on the left nav items @cameron-chilton

**Comment by cameron-chilton** [comment]
> The thick blue border still shows on the cards and on the left nav items @cameron-chilton

Removed focus and active styles from USWDS, ready for re-test.

**Comment by fiorine** [comment]
Ok, this one looks good for now except for User Access / Service Chiefs merge and all supporting features. @cameron-chilton

**Comment by cameron-chilton** [comment]
closing because of merge conflicts with Admin UI branch. PR has been re-created in new branch for new PR.

**Pull request closed without merging**
