### PR TITLE
LEAF-1311 support code coverage scanning with external tools

### PR DESCRIPTION
**Pull request by patrickcgs**
Configuration updates to allow generation of code coverage with
   phpunit/php-code-coverage

   - added ./test/prepend/coverage_header.php
   - added php configuration: 
   auto_prepend_file=/var/www/html/test/prepend/coverage_header.php
   - moved xdebug configuration to /usr/local/etc/php/conf.d/xdebug.ini
   - added profile tracing, enable by adding to request:
   ?XDEBUG_PROFILE=profile
   - added support for ide breakpoints; enable by adding to request:
   ?XDEBUG_SESSION_START=leafide
    You may need to configure xdebug.remote_host for your environment
   - added script for running tests and generating report:
    cd ./docker
    docker-compose exec php /var/www/html/test/run_tests.sh

### CODE REVIEW

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- test/prepend/coverage_header.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5427172&bid=17797381)

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- test/prepend/coverage_header.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5427172&bid=17797381)

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- test/prepend/coverage_header.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5427172&bid=17797381)

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- test/prepend/coverage_header.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5427172&bid=17797381)

**Comment by patrickcgs** [comment]
Recreated PR https://github.com/VHAINNOVATIONS/LEAF/pull/930

**Pull request closed without merging**
