### PR TITLE
Dev: Merge Preprod into Dev after Preprod Hotfix Release

### PR DESCRIPTION
**Pull request by gsteinhoff**

### CODE REVIEW

**Review by Pelentan — APPROVED** [review]
One thing that will need to be updated but not important now.  docs/InstallationConfiguration.md  line 81.  Should be docker-compose up --build -d.  Before "build" it needs dash-dash.

**Review by iainapostolos — APPROVED** [review]
All good.

**Review by pete-nerantzinis — APPROVED** [review]
Looks good also added the double dash to build

**Review by iainapostolos — APPROVED** [review]
Good.

**Pull request merged**
