### PR TITLE
fixing phpunit test scripts draft

### PR DESCRIPTION
**Pull request by dogwang94**
merge LEAF-1452-Resolve-failed-PHP-unit-test to dev

### CODE REVIEW

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5434316&bid=17820639)

**Comment by dastan-rahimi** [comment]
Tests are failing in in LEAF_Request_Portal

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 7
           

Complexity increasing per file
==============================
- test/LEAF_Nexus_Tests/tests/api/controllers/EmployeeControllerTest.php  2
- test/LEAF_Request_Portal_Tests/tests/api/ServiceControllerTest.php  24
         

Clones added
============
- test/LEAF_Request_Portal_Tests/tests/api/FormControllerTest.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5434316&bid=17820639)

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 7
           

Complexity increasing per file
==============================
- test/LEAF_Nexus_Tests/tests/api/controllers/EmployeeControllerTest.php  2
- test/LEAF_Request_Portal_Tests/tests/api/ServiceControllerTest.php  24
         

Clones added
============
- test/LEAF_Request_Portal_Tests/tests/api/FormControllerTest.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5434316&bid=17820639)

**Comment by patrickcgs** [comment]
One test failing

image

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- test/LEAF_Request_Portal_Tests/tests/api/ServiceControllerTest.php  24
- test/LEAF_Nexus_Tests/tests/api/controllers/EmployeeControllerTest.php  6
- test/LEAF_Request_Portal_Tests/tests/api/WorkflowControllerTest.php  2
         

Clones added
============
- test/LEAF_Request_Portal_Tests/tests/api/ServiceControllerTest.php  2
- test/LEAF_Request_Portal_Tests/tests/api/FormControllerTest.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5434316&bid=17820639)

**Comment by patrickcgs** [comment]
Tests now pass on my local machine, thanks!

image

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 2
           

Complexity increasing per file
==============================
- test/LEAF_Nexus_Tests/tests/api/controllers/EmployeeControllerTest.php  3
- test/LEAF_Request_Portal_Tests/tests/api/ServiceControllerTest.php  36
- test/LEAF_Request_Portal_Tests/tests/api/WorkflowControllerTest.php  2
         

Clones added
============
- test/LEAF_Request_Portal_Tests/tests/api/FormControllerTest.php  2
         

Clones removed
==============
+ test/LEAF_Request_Portal_Tests/tests/api/ServiceControllerTest.php  -17
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5434316&bid=17820639)

**Pull request merged**
