### PR TITLE
feature/LEAF-1939: Create 404 Page for Stateless Transition

### PR DESCRIPTION
**Pull request by cameron-chilton**
New custom page for users to see when the page they are looking for does not exist.

- New php page
- 2 New image files for leaf images
- CSS changes for new container
- Variable applied for return to Launchpad link

Screen Shot 2020-11-12 at 11 23 24 AM

### CODE REVIEW

**Comment by thomasnguyen95** [comment]
Can we move the .png images to /libs/img/ or another directory? 
If the 404 page is going to be used across portals/orgcharts we should keep the assets relative to both portal and orgchart not just portal.

**Review by dastan-rahimi — APPROVED** [review]

**Comment by dastan-rahimi** [comment]
> Can we move the .png images to /libs/img/ or another directory?
> If the 404 page is going to be used across portals/orgcharts we should keep the assets relative to both portal and orgchart not just portal.

Cameron, Please make this change

**Comment by cameron-chilton** [comment]
> Can we move the .png images to /libs/img/ or another directory?
> If the 404 page is going to be used across portals/orgcharts we should keep the assets relative to both portal and orgchart not just portal.



> Can we move the .png images to /libs/img/ or another directory?
> If the 404 page is going to be used across portals/orgcharts we should keep the assets relative to both portal and orgchart not just portal.

**Comment by cameron-chilton** [comment]
closed accidentally

**Comment by cameron-chilton** [comment]
> > Can we move the .png images to /libs/img/ or another directory?
> > If the 404 page is going to be used across portals/orgcharts we should keep the assets relative to both portal and orgchart not just portal.
> 
> Cameron, Please make this change

Images moved to the 'libs/img' folder. There is a docker issue on my local, I'm not able to see the images but Jeremy says they are working on his PC.

**Review by thomasnguyen95 — APPROVED** [review]

**Pull request merged**
