### PR TITLE
Feature/report builder 2d export

### PR DESCRIPTION
**Pull request by mgaoVA**

### CODE REVIEW

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity decreasing per file
==============================
+ LEAF_Request_Portal/api/RESTfulResponse.php  -3
         

Clones removed
==============
+ LEAF_Request_Portal/api/RESTfulResponse.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5205851&bid=17074191)

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity decreasing per file
==============================
+ LEAF_Request_Portal/api/RESTfulResponse.php  -3
         

Clones removed
==============
+ LEAF_Request_Portal/api/RESTfulResponse.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5205851&bid=17074191)

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity decreasing per file
==============================
+ LEAF_Request_Portal/api/RESTfulResponse.php  -3
         

Clones removed
==============
+ LEAF_Request_Portal/api/RESTfulResponse.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5205851&bid=17074191)

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ LEAF_Request_Portal/api/RESTfulResponse.php  -3
         

Clones removed
==============
+ LEAF_Request_Portal/api/RESTfulResponse.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5205851&bid=17074191)

**Comment by mgaoVA** [comment]
closing to create new PR due to new requirements

**Pull request closed without merging**
