### PR TITLE
Leaf713 table input format

### PR DESCRIPTION
**Pull request by jeanmarcablevets**

### CODE REVIEW

**Comment by nathanws** [comment]
Be sure to rebase this onto the `dev` branch. A good primer on rebasing: 

https://dev.to/maxwell_dev/the-git-rebase-introduction-i-wish-id-had

All that boils down to:

1. Ensure the `dev` branch is up to date on your machine
1. Checkout your branch
1. `git rebase dev`
1. Resolve any merge conflicts

**Comment by nathanws** [comment]
If the table only contains one row, it does not allow that row to be deleted. Which means the user is stuck with having at least one row of data within the table. So they should be able to delete that row.

The Report Builder is displaying the table, however it is taking up the entire width of the browser, it should only be as wide as necessary to contain the data.

When editing a Table in Firefox, none of the arrows/delete buttons work in the Form Editor and when editing a Request.

The UI when editing a Table in IE is not displaying correctly.
capture
capture2
capture3

**Comment by apgates** [comment]
Changes have been request in Jira.

**Comment by nathanws** [comment]
The editing and save functionality aren't working in Chrome and Firefox. 

When editing the Table input in the Form Editor, it sometimes adds an extra column when it is saved.

**Comment by jeanmarcablevets** [comment]
Question about feedback @mgaoVA :
1)  I use a 1px border to separate the dialog box columns.  Should I use a different border?

**Comment by jeanmarcablevets** [comment]
@jeremyrl addressed in commit `a98`

**Comment by jeanmarcablevets** [comment]
Created a new branch called `table_input` to continue work

**Pull request closed without merging**
