### PR TITLE
feature/query-data-filter2

### PR DESCRIPTION
**Pull request by mgaoVA**
This expands availability of the x-filterData option to all Request Portal APIs.

### CODE REVIEW

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Clones added
============
- LEAF_Request_Portal/api/RESTfulResponse.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5405155&bid=17718097)

**Comment by dastan-rahimi** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Clones added
============
- LEAF_Request_Portal/api/RESTfulResponse.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/VALEAF/LEAF/pullRequest?prid=5405155&bid=17718097)

**Comment by patrickcgs** [comment]
@mgaoVA -- I noticed that when using **_format=htmltable_**, the generated output would include more headers than specified by the new query parameter x-filterData.  However, when using format=csv or format=xml, only the headers specified were present in the output.

**Comment by mgaoVA** [comment]
Nice find, @patrickcgs . The extra headers are showing up because format=htmltable is applying a predefined set of properties, which was originally intended to filter out headers for convenience in a specific context. 

format=htmltable will need to be updated in the future to include better integration with x-filterData, as well as improve consistency within htmltable's property names.

For this particular PR, we can proceed as-is.

**Pull request merged**
